language: r
sudo: required
dist: trusty
git:
  submodules: false

warnings_are_errors: false

r:
    - oldrel
    - release
    - devel

r_github_packages:
    - jimhester/covr
    - jimhester/lintr

r_binary_packages:
    - devtools
    - roxygen2

env:
  - global:
    - _R_CHECK_FORCE_SUGGESTS_=0
    - LINTR_COMMENT_BOT=false
cache:
  packages: true

after_success:
    - Rscript -e 'covr::codecov()'
    - Rscript -e 'lintr::lint_package()'
